python plot_loss_as_metric.py --opt_name adam --model_name autoencoder_v0
python plot_loss_as_metric.py --opt_name nadam --model_name autoencoder_v0
python plot_loss_as_metric.py --opt_name adamax --model_name autoencoder_v0
python plot_loss_as_metric.py --opt_name adagrad --model_name autoencoder_v0
python plot_loss_as_metric.py --opt_name adadelta --model_name autoencoder_v0
python plot_loss_as_metric.py --opt_name sgd --model_name autoencoder_v0
python plot_loss_as_metric.py --opt_name rmsprop --model_name autoencoder_v0
python plot_loss_as_metric.py --opt_name adam --model_name autoencoder_v1
python plot_loss_as_metric.py --opt_name adam --model_name autoencoder_v22
python plot_loss_as_metric.py --opt_name adam --model_name autoencoder_v23
